### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by RangerMauve** [tomekwi/virtual-dom-lite#1]
It'd be nice if there was a minimal example showing how to use this module.

**Comment by tomekwi** [comment]
Absolutely. Thanks for pinging on me – time to complete the docs. I’ll try to do it tomorrow.

**Comment by RangerMauve** [comment]
No rush! I was just thinking of using this library for a clone of [html-patcher](https://www.npmjs.com/package/html-patcher) called `html-patcher-light` and using it within my apps.

**Comment by tomekwi** [comment]
Sounds good! I too use this for patching a single element. I’ll let you know when I’m done!

**Comment by tomekwi** [comment]
https://github.com/tomekwi/virtual-dom-lite/tree/1f70eac#usage
https://github.com/tomekwi/virtual-dom-lite/tree/1f70eac#caveats

The implementation has changed a bit as well, in case you’ve already built something on it.

**Comment by RangerMauve** [comment]
Awesome, thanks!
